# Generated by Django 5.2.8 on 2025-11-07 17:57

import django_cpf_cnpj.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(max_length=18),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(max_length=14),
        ),
    ]
