# Generated by Django 5.2.8 on 2025-11-07 18:43

import django_cpf_cnpj.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_cnpj_alter_client_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
