# Generated by Django 5.2.8 on 2025-11-07 18:49

import django_cpf_cnpj.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_client_cnpj_alter_client_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Principal')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Secundário')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
            ],
            options={
                'verbose_name': 'Cliente (PF)',
                'verbose_name_plural': 'Clientes (PF)',
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Principal')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Secundário')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('fantasy_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome de Fantasia')),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
            ],
            options={
                'verbose_name': 'Cliente (PJ)',
                'verbose_name_plural': 'Clientes (PJ)',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
