# Generated by Django 5.2.8 on 2025-12-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
